print ("Balloonicorn is going to a party this weekend!")
print (46)
print ("It's a birthday party.")
print (22)
print ("Balloonicorn needs to make a cake for her friend.")
print (49)
print ("It will be red velvet.")
print (22)
print (True)
print (False)
print (54321)
print (type(34))
